---

bar:
  # Increase/decrease this value until the minibuffer in vim/hx/nvim have no padding. ( I just dislike it)
  height: 30 # Next Value: 77
  location: top
  background: 3E3F67ff
  font: Ubuntu Nerd Font:pixelsize=28
  spacing: 5
  right-margin: 25
  center:
    - mpd:
        host: /home/egoist/.config/mpd/socket
        anchors:
          list: &artist_album_title
            spacing: 0
            on-click:
              left: mpc --host /home/egoist/.config/mpd/socket toggle
              next: mpc --host /home/egoist/.config/mpd/socket next
              previous: mpc --host /home/egoist/.config/mpd/socket prev
            items:
              - map:
                  conditions:
                    random: {string: {text: "🔀 "}}
              - map:
                  conditions:
                    repeat: {string: {text: "🔁 "}}
              - map:
                  conditions:
                    consume: {string: {text: "✂️ "}}
              - map:
                  conditions:
                    state == playing: {string: {text: "{artist}"}}
                    state == paused: {string: {text: "{artist}", foreground: ffffff66}}
              - string: {text: " - ", foreground: ffffff66}
              - map:
                  conditions:
                    state == playing: {string: {text: "{album}"}}
                    state == paused: {string: {text: "{album}", foreground: ffffff66}}
              - string: {text: " - ", foreground: ffffff66}
              - map:
                  conditions:
                    state == playing: {string: {text: "{title}", foreground: ffa0a0ff}}
                    state == paused: {string: {text: "{title}", foreground: ffffff66}}

        content:
          map:
            conditions:
              state == offline: {string: {text: offline, foreground: ff0000ff}}
              state == stopped: {string: {text: stopped}}
              state == paused: {list: *artist_album_title}
              state == playing: {list: *artist_album_title}


  right:
    - script:
        path: /etc/profiles/per-user/egoist/bin/matcha
        args: [ '-d', '-o', '--bar=yambar']
        content: 
            - map:
                on-click:
                  left: /etc/profiles/per-user/egoist/bin/matcha --toggle
                conditions:
                  inhibit: { string: { text: " " , } } 
                  ~inhibit: { string: { text: "󰒲 ", foreground: ffffff66 } } 
    - label:
        content: { string: { text: "|" } }
    - network:
        name: enp4s0
        content:
            - map:
                conditions:
                  state == up: {string: {text: "🌐{name}: {ipv4}" } }
                  state == down: {string: {text: "🌐{name}: {ipv4}", foreground: ffffff66 } }
                  state == "not present": {string: {text: "🌐 NOT PRESENT", foreground: ffffff66 }}
                  state == unknown: {string: {text: "🌐{name}: {ipv4}", foreground: ffffff66 }}
            
    - label:
        content: { string: { text: "|" } }
    - pipewire:
        anchors:
          volume: &volume
            conditions:
              type == "source": { empty: {} }
              muted: 
                - string: {text: "{linear_volume}%", foreground: ff0000ff }
              ~muted:
                - string: {text: "{linear_volume}%"  }
        content:
          list:
            on-click:
              left: "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
              wheel-up: "wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+"
              wheel-down: "wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%-"
            items:
              - map:
                  conditions:
                    type == "sink" && ~muted:

                      - ramp:
                          tag: linear_volume
                          items:
                            - string: {text: " "}
                            - string: {text: " "}
                    type == "sink" && muted:
                      - string: {text: " 󰝟"}
              - map:
                  <<: *volume

    - label:
        content: { string: { text: "|" } }
    - clock:
        date-format: "%Y-%m-%d"
        time-format: "%T"
        content:
          - string: {text: "  {date} "}
          - string: {text: "|"}
          - string: {text: "  {time}" }


  left:
    # https://codeberg.org/dnkl/yambar/issues/300
    # - i3:
    #     content:
    #       "":
    #         map:
    #           default: { string: { text: "{name}", margin: 5 } }
    #           conditions:
    #             state == focused: { string: { text: "{name}", margin: 5, foreground: ff0000ff } }
    # - label:
    #     content: { string: { text: "|" } }
    - cpu:
        poll-interval: 2500
        content:
          map:
            conditions:
             id == -1 && cpu <= 80: { string: {text: "  {cpu}%" } }
             id == -1 && cpu > 80: { string: {text: "  {cpu}%", foreground: ff0000ff} }

    - label:
        content: { string: { text: "|" } }
    - mem:
        poll-interval: 2500
        content:
          map:
            conditions:
              percent_used <= 80: { string: {text: "  {used:mb}MB" } }
              percent_used > 80: { string: {text: "  {used:mb}MB", foreground: ff0000ff} }
