id = 677226551607033903
hosts = ["/home/egoist/.config/mpd/socket"]

[format]
details = "$title"
state = "$artist / $album"
timestamp = "elapsed"
large_image = "notes"
small_image = "notes"
large_text = ""
small_text = ""
