theme = "amberwood"
[editor]
  rulers = [100]
  text-width = 100
  auto-pairs = false

[editor.cursor-shape]
  insert = "bar"

[editor.lsp]
  display-signature-help-docs = false


[editor.soft-wrap]
  enable = true
  wrap-at-text-width = true


[keys.normal]
  "X" = [ "extend_line_up", "extend_to_line_bounds" ]


[editor.indent-guides]
  render = true

[editor.file-picker]
  hidden = false
