theme = "amberwood"
[editor]
  rulers = [120]
  text-width = 120
  auto-pairs = false
  bufferline = "multiple"

[editor.cursor-shape]
  insert = "bar"

[editor.lsp]
  display-signature-help-docs = false


[editor.soft-wrap]
  enable = true
  wrap-at-text-width = true
  wrap-indicator = "⭸"


[editor.indent-guides]
  render = true

[editor.file-picker]
  hidden = false

[editor.smart-tab]
  enable = false
